### ISSUE TITLE
Add tables

### ISSUE THREAD

**Issue by amine-aboufirass** [amine-aboufirass/pandoc-latex-writer#6]
Add syntax to generate a simple latex table:
- control geometry, specifically column widths
- table reference

**Comment by awa5114** [comment]
Support following types of tables (for now):
- Simple tables
- Grid tables

Two variants, one with explicit column width and one with the implicit column width based on `--column-width` command line argument.

# Explicit column width with a simple table
```
:::: {#my-simple-table .table Right=2cm Left = 1cm}
: Simple table

  Right     Left     Center     Default
-------     ------ ----------   -------
     12     12        12            12
    123     123       123          123
      1     1          1             1
::::
```
# Implicit column width with a simple table
Won't require a `Div` wrapper. 

```
: Simple table

  Right     Left     Center     Default
-------     ------ ----------   -------
     12     12        12            12
    123     123       123          123
      1     1          1             1
```
Likewise for Grid tables.

**Comment by amine-aboufirass** [comment]
Still need to add table references

**Comment by amine-aboufirass** [comment]
May later require improvements on spacing between the caption and the table
